import Link from 'next/link';
import styles from '../styles/disclaimer.module.css';

export default function Disclaimer() {
  return (
    <div className={styles.container}>
      <div className={styles.background}>
        <img src="/disclaimerBackground.png" alt="Background" className={styles.backgroundImage} />
      </div>

      <header className={styles.header}>

        <Link href="/">
        <img src="/backButton.png" alt="Button" className={styles.headerButton} />
        </Link>
        <h1 className={styles.headerheading}>LIGAFUTURE</h1>
      </header>

      <div className={styles.topSection}>
        <h1 className={styles.topheading}>Disclaimer</h1>
        <h1 className={styles.explanation}>Prediction is based on AI.</h1>
      </div>

      <p className={styles.text}>
      The content on this website, including tarot card readings and interpretations, is generated by artificial intelligence. While we strive for accuracy and relevance, please note that these readings are for entertainment purposes only and should not be considered professional advice. 
      </p>

      <Link href="/prequestion">
        <button className={styles.startButton}>Confirm</button>
      </Link>
    </div>
  );
}

